name: Build and Upload APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:st
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./YOUR_FOLDER_NAME # এখানে আপনার প্রজেক্ট ফোল্ডারের নাম দিন

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./YOUR_FOLDER_NAME # এখানে আপনার প্রজেক্ট ফোল্ডারের নাম দিন

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Baskandi-Azan-APK
          path: build/app/outputs/flutter-apk/app-release.apk
